import { useState } from 'react'
import { Check, ChevronDown, Copy, Mail, PenLine, RefreshCw } from 'lucide-react'
import { useBrief, useRegenerateBrief } from '../../api/hooks'
import type { AccountBrief, AccountDetail } from '../../api/types'
import { TYPE_LABEL, shortDate } from '../../lib/format'
import { Button, ErrorState, Skeleton } from '../ui'
import { LEVEL_STYLES, cx } from '../../lib/styles'
import { useMarkDone } from '../useMarkDone'

/** AI summary + next best action + outreach draft. Falls back to the rules engine transparently. */
export function BriefSection({ account }: { account: AccountDetail }) {
  const id = account.customer.id
  const brief = useBrief(id)
  const regenerate = useRegenerateBrief(id)
  const data = brief.data

  return (
    <div className="space-y-4">
      <section aria-labelledby="brief-title" className="rounded-xl border border-line bg-surface p-5">
        <div className="mb-2 flex items-center justify-between gap-3">
          <h3 id="brief-title" className="text-sm font-semibold text-ink-soft">
            The short version
          </h3>
          <div className="flex items-center gap-2">
            {data && <SourceBadge brief={data} />}
            <Button
              size="sm"
              variant="ghost"
              aria-label="Regenerate brief"
              title="Regenerate brief"
              loading={regenerate.isPending}
              icon={<RefreshCw className="size-3.5" aria-hidden />}
              onClick={() => regenerate.mutate()}
            />
          </div>
        </div>
        {/* The rules summary is available instantly; the brief replaces it when ready. */}
        <p className="font-serif text-[17px] leading-relaxed text-ink">{data?.summary ?? account.insight.summary}</p>
        {brief.isPending && <p className="mt-2 text-xs text-ink-faint">Writing the brief…</p>}
      </section>

      {brief.error ? (
        <ErrorState error={brief.error} onRetry={() => brief.refetch()} />
      ) : !data ? (
        <Skeleton className="h-44 w-full rounded-xl" />
      ) : (
        <NextActionCard account={account} brief={data} />
      )}
    </div>
  )
}

function SourceBadge({ brief }: { brief: AccountBrief }) {
  const label = brief.source === 'llm' ? `Written by ${brief.model}` : 'Built from your history'
  const title =
    brief.source === 'llm'
      ? 'Generated by the configured LLM from this account’s interactions, then checked against them.'
      : brief.fallback_reason
        ? `The AI answer was rejected (${brief.fallback_reason}), so this was built by the rules engine.`
        : 'No LLM configured: built by the rules engine from this account’s interactions.'
  return (
    <span title={title} className="rounded-full bg-harbor-soft px-2 py-0.5 text-xs font-medium text-harbor">
      {label}
      {brief.fallback_reason && ' (fallback)'}
    </span>
  )
}

function NextActionCard({ account, brief }: { account: AccountDetail; brief: AccountBrief }) {
  const { markDone, pendingId } = useMarkDone()
  const [showDraft, setShowDraft] = useState(false)
  const [showEvidence, setShowEvidence] = useState(true)
  const level = account.insight.priority_level
  const hasDraft = brief.suggested_message.trim().length > 0
  const canComplete = account.insight.open_follow_up

  return (
    <section
      aria-labelledby="next-action-title"
      className="overflow-hidden rounded-xl border border-line bg-surface"
    >
      <div className={cx('h-1', LEVEL_STYLES[level].bar)} aria-hidden />
      <div className="p-5">
        <h3 className="text-sm font-semibold text-ink-soft">Next best action</h3>
        <p id="next-action-title" className="mt-1 text-xl font-semibold leading-snug text-balance">
          {brief.next_action}
        </p>
        <p className="mt-2 text-sm leading-relaxed text-ink-soft">{brief.reason}</p>
        {brief.insufficient_information && (
          <p className="mt-2 text-sm text-week">There isn’t enough history to be confident about this.</p>
        )}
        {brief.recipient && hasDraft && (
          <p className="mt-3 text-sm">
            <span className="text-ink-faint">Reach out to </span>
            <span className="font-semibold">{brief.recipient.name}</span>
            <span className="text-ink-faint">, {brief.recipient.role}</span>
          </p>
        )}

        <div className="mt-4 flex flex-wrap gap-2">
          {hasDraft && (
            <Button
              variant={showDraft ? 'secondary' : 'primary'}
              icon={<PenLine className="size-4" aria-hidden />}
              onClick={() => setShowDraft((v) => !v)}
              aria-expanded={showDraft}
            >
              {showDraft ? 'Hide outreach' : 'Draft outreach'}
            </Button>
          )}
          {canComplete && (
            <Button
              icon={<Check className="size-4" aria-hidden />}
              loading={pendingId === account.customer.id}
              onClick={() => markDone(account.customer.id, account.customer.name)}
            >
              Mark follow-up done
            </Button>
          )}
        </div>

        {showDraft && hasDraft && (
          <OutreachDraft
            brief={brief}
            onSent={(subject) => markDone(account.customer.id, account.customer.name, `Sent email “${subject}”.`)}
            canComplete={canComplete}
          />
        )}

        {brief.talking_points.length > 0 && (
          <div className="mt-5">
            <h4 className="text-sm font-semibold">Talking points</h4>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-ink-soft marker:text-ink-faint">
              {brief.talking_points.map((point) => (
                <li key={point}>{point}</li>
              ))}
            </ul>
          </div>
        )}

        {brief.evidence.length > 0 && (
          <div className="mt-5 border-t border-line pt-4">
            <button
              type="button"
              className="flex items-center gap-1.5 text-sm font-semibold"
              aria-expanded={showEvidence}
              onClick={() => setShowEvidence((v) => !v)}
            >
              <ChevronDown className={cx('size-4 transition-transform', !showEvidence && '-rotate-90')} aria-hidden />
              Based on {brief.evidence.length} {brief.evidence.length === 1 ? 'interaction' : 'interactions'}
            </button>
            {showEvidence && (
              <ul className="mt-3 space-y-2.5">
                {brief.evidence.map((ev) => (
                  <li key={ev.interaction_id} className="border-l-2 border-harbor/30 pl-3 text-sm">
                    <p className="text-xs text-ink-faint">
                      {shortDate(ev.occurred_at)}, {TYPE_LABEL[ev.type].toLowerCase()}
                    </p>
                    <p className="text-ink-soft">{ev.quote}</p>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>
    </section>
  )
}

function OutreachDraft({
  brief,
  onSent,
  canComplete,
}: {
  brief: AccountBrief
  onSent: (subject: string) => void
  canComplete: boolean
}) {
  const [subject, setSubject] = useState(brief.message_subject)
  const [body, setBody] = useState(brief.suggested_message)
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      setCopied(false)
    }
  }

  const mailto = brief.recipient
    ? `mailto:${brief.recipient.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    : undefined

  return (
    <div className="mt-4 space-y-3 rounded-lg border border-line bg-paper/60 p-4">
      {brief.recipient && (
        <p className="text-xs text-ink-faint">
          To: {brief.recipient.name} &lt;{brief.recipient.email}&gt;
        </p>
      )}
      <label className="block">
        <span className="text-xs font-medium text-ink-soft">Subject</span>
        <input
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
          className="mt-1 h-9 w-full rounded-md border border-line-strong bg-surface px-3 text-sm"
        />
      </label>
      <label className="block">
        <span className="text-xs font-medium text-ink-soft">Message (edit before sending)</span>
        <textarea
          value={body}
          onChange={(e) => setBody(e.target.value)}
          rows={8}
          className="mt-1 w-full rounded-md border border-line-strong bg-surface p-3 text-sm leading-relaxed"
        />
      </label>
      <div className="flex flex-wrap gap-2">
        <Button size="sm" icon={copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />} onClick={copy}>
          {copied ? 'Copied' : 'Copy'}
        </Button>
        {mailto && (
          <a
            href={mailto}
            className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-line-strong bg-surface px-2.5 text-xs font-semibold hover:bg-paper"
          >
            <Mail className="size-3.5" aria-hidden />
            Open in email app
          </a>
        )}
        {canComplete && (
          <Button size="sm" variant="primary" onClick={() => onSent(subject)}>
            Log as sent
          </Button>
        )}
      </div>
    </div>
  )
}
